### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [mrdvt92/perl-GD-Graph-Polar#1]
Please see https://rt.cpan.org/Ticket/Display.html?id=129149

**Comment by mrdvt92** [comment]
I've pushed a new release.  I'll check CPAN testers in the morning...

**Comment by mrdvt92** [comment]
I've pushed another release.  I'll check CPAN testers in the morning...

**Comment by mrdvt92** [comment]
The latest tweaks make testers happy.

0.20 - 2022-09-22
  - Updated rbgfile method to fixed issue calling Graphics::ColorNames which requires files to be true according to File::Spec::Functions::file_name_is_absolute
